### ISSUE TITLE
DOES NOT WORK PLEASE HELP

### ISSUE THREAD

**Issue by Yakuhito** [hofill/temp#1]
HELLO SIR,

I AM TRYING TO HACK. I GET ERROR. HOW TO FIX?

```
yakuhito@catstation:/tmp/temp$ ./test.php 
./test.php: line 1: ?php: No such file or directory
TEST
./test.php: line 5: syntax error near unexpected token `newline'
./test.php: line 5: `?>'
yakuhito@catstation:/tmp/temp$
```

**Comment by hofill** [comment]
@Yakuhito 
> HELLO SIR,
>
> I AM TRYING TO HACK. I GET ERROR. HOW TO FIX?

It's understandable that you might be worried if a program is not working as expected. However, it's important to first verify that you are using the program correctly. In this case, it seems that you need to use the command `php test.php` to start the program. If you are not using this command to start the program, then it's likely that the issue is with your attempt to use it rather than with the program itself.

It's also possible that there may be other issues preventing the program from functioning properly, such as incorrect file permissions or missing dependencies. In these cases, it may be helpful to check the documentation or seek assistance from the developers or community to troubleshoot the issue.

Overall, it's important to carefully follow the instructions for using a program and to carefully consider any potential issues that may be causing it to not work as expected.
